### PR TITLE
Update Set-CMSiteMaintenanceTask.md

### PR DESCRIPTION
**Pull request by GambitC90**
Set-CMSiteMaintenanceTask -SiteCode "CM1" -MaintenanceTaskName "Backup" -DaysOfWeek Friday throws an error "Set-CMSiteMaintenanceTask : No object corresponds to the specified parameters." you need to specify the full Task Name.

### CODE REVIEW

**Comment by PRMerger17** [comment]
@GambitC90 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by aczechowski** [comment]
Hi @GambitC90, thanks for the contribution. We're actually not currently approving edits, there's a sync issue with the main repo that actually publishes. I'm still working on fixing the sync. Once I do, then I'll come review these PRs.

**Comment by GambitC90** [comment]
> Hi @GambitC90, thanks for the contribution. We're actually not currently approving edits, there's a sync issue with the main repo that actually publishes. I'm still working on fixing the sync. Once I do, then I'll come review these PRs.

No problem, is it okay for me to keep supplying edits? I have this activity as part of my "Contribute to the success or others" on my MSConnect so I want to keep up on it when I find issues, but at the same time don't want to cause you issues... Please advise.

**Comment by GambitC90** [comment]
Put changes in the Private Repo...

**Pull request closed without merging**
