### PR TITLE
Fixed examples to not use C:, included note to use CM Drive

### PR DESCRIPTION
**Pull request by ChrisKibble**
All of the sample pages included examples where ConfigMgr cmdlets were running from C:\>, which isn't possible.  They must be run from the CMDrive.  Additionally, added a comment to all pages with examples that note this and point back to the getting started page that shows how this is done.  There are many pages with empty examples that I changed to a sample site code (XYZ:\) so that when they're filled out when someone contributes examples.

Contribution for #MMS2019Docathon

@aczechowski I'd like to include this one for consideration for most impactful - having new system administrators see the bad examples could frustrate those new to trying to automate CM with PowerShell.

### CODE REVIEW

**Comment by PRMerger8** [comment]
@ChrisKibble : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger8** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.

**Comment by aczechowski** [comment]
Thanks @ChrisKibble for the contribution! I'll review after the end of the MMS contest.
@mumian disregard, I'll take care of this one.

#hold-off
(reviewers, please don't edit - I'll take care of it.)

**Comment by PRMerger12** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger12** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.

**Comment by PRMerger16** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger16** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.

**Comment by PRMerger16** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger16** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.

**Comment by PRMerger16** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger16** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.

**Comment by PRMerger17** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger17** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.

**Comment by PRMerger17** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger17** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.

**Comment by PRMerger17** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger17** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.

**Comment by PRMerger17** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger18** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.

**Comment by PRMerger18** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger18** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.

**Comment by PRMerger18** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.

**Comment by PRMerger18** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger18** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.

**Comment by PRMerger18** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger18** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.

**Comment by PRMerger19** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger19** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.

**Comment by PRMerger19** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger19** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by PRMerger19** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by PRMerger19** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger19** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger19** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by PRMerger19** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by PRMerger20** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger20** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger20** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by PRMerger20** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger20** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by PRMerger20** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger6** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by PRMerger6** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger6** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by PRMerger6** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger6** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by PRMerger6** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger6** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by PRMerger6** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger6** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by PRMerger6** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger6** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by PRMerger6** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by PRMerger7** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger7** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger7** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by PRMerger7** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by PRMerger7** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger7** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger8** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by PRMerger8** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger8** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger8** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by PRMerger8** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by PRMerger8** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger9** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by PRMerger9** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by PRMerger9** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger9** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by PRMerger9** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger9** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by PRMerger9** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by PRMerger9** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger10** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by PRMerger10** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger10** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by PRMerger10** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger10** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by PRMerger10** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger10** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger10** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by PRMerger12** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger12** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by PRMerger12** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger12** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by PRMerger12** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger12** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by PRMerger12** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger12** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by PRMerger12** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger12** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by PRMerger13** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by PRMerger13** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by PRMerger13** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger13** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by PRMerger13** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger13** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by PRMerger13** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger14** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by PRMerger14** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger15** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by PRMerger15** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by PRMerger15** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger15** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger16** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by PRMerger16** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by PRMerger16** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger16** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by PRMerger16** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger16** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by PRMerger17** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger17** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by PRMerger17** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger17** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by PRMerger17** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger17** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by PRMerger17** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger17** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by PRMerger18** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger18** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by PRMerger18** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger18** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by PRMerger18** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger18** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by PRMerger18** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by PRMerger18** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger19** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by PRMerger19** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger19** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by PRMerger19** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger19** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by PRMerger19** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger20** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger20** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger20** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by PRMerger20** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger20** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by PRMerger20** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger20** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by PRMerger6** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by PRMerger6** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger6** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by PRMerger7** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger7** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by PRMerger8** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger8** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger8** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by PRMerger8** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by PRMerger8** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger8** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger8** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by PRMerger9** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger9** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by PRMerger9** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger9** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by PRMerger9** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger9** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by PRMerger9** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger9** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by PRMerger9** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger9** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by PRMerger9** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger9** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by PRMerger10** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by PRMerger10** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger10** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by PRMerger10** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger10** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger10** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by PRMerger10** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger10** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by PRMerger10** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger10** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger10** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by PRMerger10** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger10** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger10** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by PRMerger12** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger12** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger12** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by PRMerger12** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger12** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger12** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by PRMerger12** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger12** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger12** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by PRMerger12** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger12** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger12** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by PRMerger12** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger12** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by PRMerger12** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger13** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by PRMerger13** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by PRMerger13** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by PRMerger17** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger18** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by PRMerger19** [comment]
@aczechowski : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger20** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 Commits Count | This PR contains more than 15 commits.

**Comment by aczechowski** [comment]
I started making individual edits, because I'm worried about a special character that GitHub is picking up at the start of each modified file (with a larger metadata cleanup effort in flight, I worry about potential conflicts). Then I did the math, and with the number of files in this PR it will take me hours to do that. 😢 So I figure out the process to make a bulk edit for the locales in the URLs, which is the primary issue. Once the build completes, I'll just merge it. If there is any conflict with the metadata, I'll deal with it then.

**Pull request merged**
