### PR TITLE
Added description text.

### PR DESCRIPTION
**Pull request by Skatterbrainz**

### CODE REVIEW

**Comment by aczechowski** [comment]
FYI we're currently having an issue with accepting public contributions to the ConfigMgr PowerShell content. So this will be on hold for a while...

**Comment by Skatterbrainz** [comment]
Awww man.  Bummer.  I understand.

**Comment by PRMerger8** [comment]
@Skatterbrainz : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by aczechowski** [comment]
Thanks @Skatterbrainz for adding this example!

Same story as before, due to the fixed issue, I can't accept this PR as-is. But I was able to bring our changes over to our private repository (from where we publish). So I'm going to close this PR, but your changes should go live with daily publishing later this afternoon (8/25 4pm)

**Pull request closed without merging**
