### PR TITLE
fix Set-Location $env:SMS_ADMIN_UI_PATH\..\

### PR DESCRIPTION
**Pull request by lelloz0**
the $env:SMS_ADMIN_UI_PATH\..\ variable in Set-Location needs to be wrapped in " " to work properly

### CODE REVIEW

**Comment by PRMerger18** [comment]
@lelloz0 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by aczechowski — APPROVED** [review]
Good catch, thank you @lelloz0 for the contribution! 😄

**Comment by lelloz0** [comment]
my pleasure @aczechowski ! I still don't see the change in the public doc though: https://docs.microsoft.com/en-us/powershell/sccm/overview?view=sccm-ps#import-the-configuration-manager-powershell-module

**Comment by aczechowski** [comment]
Yep, for this repository we have once daily publishing around 16:30 Pacific time. Refresh the page after that time to see your edit (and your profile picture in the list of contributors at the top of the article!) 😄

**Pull request merged**
