### PR TITLE
Add examples for Remove-CMSoftwareUpdateDeployment

### PR DESCRIPTION
**Pull request by spinydelta**
Added two examples on using Remove-CMSoftwareUpdateDeployment.

### CODE REVIEW

**Comment by PRMerger8** [comment]
@spinydelta : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@aczechowski : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by aczechowski — APPROVED** [review]
Thank you @spinydelta for contributing these examples! I made a couple of minor tweaks for style. Changes should be published later today I think. 😄

**Comment by aczechowski** [comment]
And thanks for your first contribution to sccm-docs-powershell-ref! 🎉

**Pull request merged**
