### PR TITLE
Update Invoke-CMWmiQuery.md

### PR DESCRIPTION
**Pull request by baardhermansen**
Added PowerShell as code identifier. 
Corrected text where command is using class SMS_Application (was incorrectly SMS_Site).

### CODE REVIEW

**Comment by PRMerger5** [comment]
@baardhermansen : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger-2** [comment]
@aczechowski : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by aczechowski — APPROVED** [review]
Thanks @baardhermansen for the contribution. I reverted the changes to the syntax section, as those are auto-generated with PlatyPS. The next time we run that tool, it will either throw a fit over that conflict, or it will just reset it. To get that behavior changed, file feedback against PlatyPS (if it doesn't already exist): https://github.com/PowerShell/platyPS/issues

**Comment by baardhermansen** [comment]
> I reverted the changes to the syntax section, as those are auto-generated with PlatyPS. The next time we run that tool, it will either throw a fit over that conflict, or it will just reset it. To get that behavior changed, file feedback against PlatyPS (if it doesn't already exist): https://github.com/PowerShell/platyPS/issues

Thanks for the explanation. Seems PlatyPS are working on that particular fix.

**Pull request merged**
