### PR TITLE
Update Remove-CMObjectSecurityScope.md

### PR DESCRIPTION
**Pull request by gwblok**
Adding a more real world example by connecting the commands together.

### CODE REVIEW

**Comment by PRMerger18** [comment]
@gwblok : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger19** [comment]
@aczechowski : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by aczechowski — APPROVED** [review]
Thanks @gwblok for the contribution! I made a little tweak to flip example 2's description back up in that section. I also added the "powershell" tag to the code block, which adds syntax formatting. 😄 It should go on the other example code blocks...save that for another edit some day!

If you're going to do more contributions, take a look at the PowerShell-specific [style guide](https://docs.microsoft.com/en-us/powershell/scripting/community/contributing/powershell-style-guide?view=powershell-7#formatting-command-syntax-elements), which has a number of recommendations. The [editorial checklist](https://docs.microsoft.com/en-us/powershell/scripting/community/contributing/editorial-checklist?view=powershell-7) is a good summary.

**Comment by gwblok** [comment]
Thanks for the feedback Aaron.  I typically copy the example code block
above and change it.  I noticed after I committed that it didn't have the
powershell tag, and that I forgot to change the example number.  Once I
made the commit, I didn't actually know how to fix the edit.  Still
learning this github commit / pull request thing. Really appreciate you
explaining things.  Once the posts go live, I'll check them out to see how
you've edit them so I'll have a better idea on how to post larger examples
in the future.

Gary

**Pull request merged**
