### PR TITLE
Added example code for connecting to unknown site name

### PR DESCRIPTION
**Pull request by ChrisKibble**
Added PowerShell example.

#MMS2019Docathon

### CODE REVIEW

**Comment by PRMerger18** [comment]
@ChrisKibble : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by aczechowski** [comment]
Thanks @ChrisKibble for the contribution! I'll review after the end of the contest.

#hold-off
(reviewers, please don't edit - I'll take care of it.)

**Comment by PRMerger15** [comment]
@ChrisKibble : Thanks for your contribution! The author, @aczechowski, has been notified to review your proposed change.

**Comment by aczechowski** [comment]
Thanks @ChrisKibble looks good
#sign-off

**Pull request merged**
