### PR TITLE
Updated descriptions for parameters

### PR DESCRIPTION
**Pull request by JordanTheITGuy**
Updated various descriptions around the various parameters as well as a note about a specific parameter that has an open Bug - See Adam Meltzer for details of the bug.

I added a Note - about what is and what isn't supported in the current parameter usage rather than calling it out as a bug.

### CODE REVIEW

**Comment by aczechowski** [comment]
FYI we're currently having an issue with accepting public contributions to the ConfigMgr PowerShell content. So this will be on hold for a while...

**Comment by JordanTheITGuy** [comment]
Thanks for the update! 

I've got a few more thing I can think of that I would like to add to the PowerShell - stuff. Should I hold off on making more Pull requests or just do them and they will get dealt with later? 

thanks!

-J

**Comment by aczechowski** [comment]
Awesome, thanks @JordanTheITGuy! I'm hoping to have more info to share at MMS JE in a few weeks. You can go ahead and make the PRs now, but we already have a good backlog. So the more ones in progress raises the potential for merge conflicts. So maybe just double-check the open PRs that someone hasn't already done the same (or similar) change. 

Or just wait until we get things sorted

**Comment by JordanTheITGuy** [comment]
Awesome! Sounds great looking forward to getting a chance to hang out and chat again! 

I'll just hold onto them for the moment. :) Gives me a chance to hope that one of the PowerShell Dev's might be there so I can talk to their ear off for a bit about the behavior of Cmdlets on null values :D 

-J

**Comment by PRMerger8** [comment]
@JordanTheITGuy : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by aczechowski** [comment]
I finally fixed a backend issue with this repository, so I'm going through the backlog of contributions.

Due to the fixed issue, I can't accept this PR as-is. But I was able to bring our changes over to our private repository (from where we publish). I made a few tweaks, and cleaned up some other descriptions. 😉 Thanks again for the contribution!

So I'm going to close this PR, but your changes should go live with daily publishing later today (8/25 4pm)

**Pull request closed without merging**
