### PR TITLE
Added PowerShell examples and fixed Related Links format.

### PR DESCRIPTION
**Pull request by ChrisKibble**

### CODE REVIEW

**Comment by PRMerger12** [comment]
@ChrisKibble : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ChrisKibble** [comment]
Fixes #75

**Comment by PRMerger17** [comment]
@aczechowski : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by aczechowski** [comment]
#sign-off

**Comment by PRMerger17** [comment]
@aczechowski : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
