### PR TITLE
Updated Table of Content Page with New Function Links

### PR DESCRIPTION
**Pull request by ChrisKibble**
There were a large number of functions that had MD files in the list but were not listed on the main content page (ConfigurationManager.md).  I added them, put in a description when one was available to me, and then resorted the list so it remained alphabatized.

#MMS2019Docathon

### CODE REVIEW

**Comment by PRMerger16** [comment]
@ChrisKibble : Thanks for your contribution! The author, @, has been notified to review your proposed change.

**Comment by PRMerger16** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 File Change Percent | This PR contains file(s) with more than 20% file change.

**Comment by aczechowski** [comment]
Awesome sauce, thanks @ChrisKibble for making this change! 
#sign-off 

*Once merged*, this should be live with the next daily publishing process. Right now that *should* be tomorrow (Thursday, 9 May) around 11:00 Pacific time. No further action needed from you.

**Comment by PRMerger10** [comment]
@aczechowski: I'm sorry - only the author of this article, @, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by aczechowski** [comment]
Ugh, sorry, process fail. (We're working on updating all of the metadata. I have to remember to just manually merge PRs in this repo.

**Pull request merged**
