### PR TITLE
Added Scripting Example

### PR DESCRIPTION
**Pull request by gwblok**
Example of using an Array to Automate exporting of Task Sequences
Example of using Data from the Task Sequence Object in the Export (Name & Modified Date)

### CODE REVIEW

**Comment by PRMerger19** [comment]
@gwblok : Thanks for your contribution! The author, @mumian, has been notified to review your proposed change.

**Comment by PRMerger7** [comment]
@aczechowski : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger7** [comment]
@aczechowski : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by aczechowski** [comment]
#sign-off 

*Once merged*, this should be live with the next daily publishing process. Right now that *should* be tomorrow (Friday, 19 July) around 15:00 Pacific time. No further action needed from you.

(As you may have seen from other notifications, there's something wonky going on with this repository right now. I've raised a case with our support, but it's not anything you need to worry about. It's possible this might impact publishing as well per the schedule above, but I'll work it through.)

**Pull request merged**
