### PR TITLE
Update Get-CMSoftwareUpdateGroup.md

### PR DESCRIPTION
**Pull request by russrimm**
This CMSoftwareUpdateGroup should not be there

### CODE REVIEW

**Comment by PRMerger6** [comment]
@russrimm : Thanks for your contribution! The author, @, has been notified to review your proposed change.

**Comment by aczechowski** [comment]
Good catch, thanks @russrimm for fixing this!
#sign-off 

*Once merged*, this should be live with the next daily publishing process. Right now that *should* be tomorrow (Thursday, 9 May). No further action needed from you.

**Comment by PRMerger9** [comment]
@aczechowski: I'm sorry - only the author of this article, @, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by aczechowski** [comment]
Ugh...process fail. We're in the background working to fix all of the metadata, but for now, I'll just merge this myself.

**Pull request merged**
