### PR TITLE
Create New Document for New-CMTSRule

### PR DESCRIPTION
**Pull request by AdamGrossTX**
This cmdlet did not have a page.

#MMS2019Docathon

@aczechowski this is one of the new pages I spoke with you about.

### CODE REVIEW

**Comment by PRMerger17** [comment]
Microsoft authors of articles need to make updates through the private repository so the updates can be staged and validated by the current validation rules. After you review staging and fix all validation issues, you can add the sign-off comment to let the PR reviewers know the updates are ready to be merged.It's easy to access the private repo version of your articles in GitHub. Just add -pr to the URL, as follows: 
 Public repo URL: https://github.com/Microsoft/azure-docs/blob/master/articles/azure-portal-overview.md 
 Private repo URL: https://github.com/Microsoft/azure-docs-pr/blob/master/articles/azure-portal-overview.md 
 We have closed this pull request. Please resubmit the updates through the private repo. If you need perms to the private repo, [see the contributor guide instructions](https://github.com/Microsoft/azure-docs/blob/master/contributor-guide/tools-and-setup.md#permissions)

**Comment by PRMerger17** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Added or Deleted File(s) | This PR contains added or deleted file(s).
 File Change Percent | This PR contains file(s) with more than 20% file change.

**Comment by AdamGrossTX** [comment]
@aczechowski this entry was auto-closed due to needing to have a page created. Please let me know if you need me to do anything else with it to have it created/submitted.

#MMS2019Docathon

**Comment by AdamGrossTX** [comment]
This fixes #48 
#MMS2019Docathon

**Comment by aczechowski** [comment]
This is a duplicate/subset of #49, which also include this same commit. So we'll just work it in that PR. I'll keep this one closed.

**Pull request closed without merging**
